/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef PKT_TYPES_H
#define PKT_TYPES_H

//This file has been autogenerated. DO NOT modify it

typedef enum protocol_types{
	PT_PROTO_ETH,
	PT_PROTO_MPLS,
	PT_PROTO_VLAN,
	PT_PROTO_PPPOE,
	PT_PROTO_PPP,
	PT_PROTO_ARPV4,
	PT_PROTO_ICMPV4,
	PT_PROTO_IPV4,
	PT_PROTO_ICMPV6,
	PT_PROTO_ICMPV6_OPTS,
	PT_PROTO_ICMPV6_OPTS_LLADR_SRC,
	PT_PROTO_ICMPV6_OPTS_LLADR_TGT,
	PT_PROTO_ICMPV6_OPTS_PREFIX_INFO,
	PT_PROTO_IPV6,
	PT_PROTO_TCP,
	PT_PROTO_UDP,
	PT_PROTO_SCTP,
	PT_PROTO_GTPU,
	PT_PROTO_MAX__
}protocol_types_t;

typedef enum pkt_types{
	PT_ETH,
	PT_ETH_MPLS_nlabels_1,
	PT_ETH_MPLS_nlabels_2,
	PT_ETH_MPLS_nlabels_3,
	PT_ETH_MPLS_nlabels_4,
	PT_ETH_MPLS_nlabels_5,
	PT_ETH_MPLS_nlabels_6,
	PT_ETH_MPLS_nlabels_7,
	PT_ETH_MPLS_nlabels_8,
	PT_ETH_MPLS_nlabels_9,
	PT_ETH_MPLS_nlabels_10,
	PT_ETH_MPLS_nlabels_11,
	PT_ETH_MPLS_nlabels_12,
	PT_ETH_MPLS_nlabels_13,
	PT_ETH_MPLS_nlabels_14,
	PT_ETH_MPLS_nlabels_15,
	PT_ETH_MPLS_nlabels_16,
	PT_ETH_MPLS_nlabels_17,
	PT_ETH_MPLS_nlabels_18,
	PT_ETH_MPLS_nlabels_19,
	PT_ETH_MPLS_nlabels_20,
	PT_ETH_MPLS_nlabels_21,
	PT_ETH_MPLS_nlabels_22,
	PT_ETH_MPLS_nlabels_23,
	PT_ETH_MPLS_nlabels_24,
	PT_ETH_MPLS_nlabels_25,
	PT_ETH_MPLS_nlabels_26,
	PT_ETH_MPLS_nlabels_27,
	PT_ETH_MPLS_nlabels_28,
	PT_ETH_MPLS_nlabels_29,
	PT_ETH_MPLS_nlabels_30,
	PT_ETH_MPLS_nlabels_31,
	PT_ETH_MPLS_nlabels_32,
	PT_ETH_ARPV4,
	PT_ETH_ICMPV4,
	PT_ETH_ICMPV6,
	PT_ETH_IPV4,
	PT_ETH_IPV4_TCP,
	PT_ETH_IPV4_UDP,
	PT_ETH_IPV4_UDP_GTPU,
	PT_ETH_IPV4_SCTP,
	PT_ETH_IPV6,
	PT_MAX__
}pkt_types_t;

const int protocol_offsets_bt[PT_MAX__][PT_PROTO_MAX__] = {
	/* ETH */ {0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_1 */ {0,14,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_2 */ {0,18,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_3 */ {0,22,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_4 */ {0,26,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_5 */ {0,30,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_6 */ {0,34,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_7 */ {0,38,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_8 */ {0,42,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_9 */ {0,46,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_10 */ {0,50,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_11 */ {0,54,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_12 */ {0,58,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_13 */ {0,62,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_14 */ {0,66,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_15 */ {0,70,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_16 */ {0,74,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_17 */ {0,78,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_18 */ {0,82,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_19 */ {0,86,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_20 */ {0,90,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_21 */ {0,94,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_22 */ {0,98,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_23 */ {0,102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_24 */ {0,106,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_25 */ {0,110,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_26 */ {0,114,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_27 */ {0,118,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_28 */ {0,122,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_29 */ {0,126,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_30 */ {0,130,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_31 */ {0,134,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/MPLS_nlabels_32 */ {0,138,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/ARPV4 */ {0,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/ICMPV4 */ {0,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/ICMPV6 */ {0,-1,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/IPV4 */ {0,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
	/* ETH/IPV4/TCP */ {0,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,34,-1,-1,-1},
	/* ETH/IPV4/UDP */ {0,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,34,-1,-1},
	/* ETH/IPV4/UDP/GTPU */ {0,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,34,-1,42},
	/* ETH/IPV4/SCTP */ {0,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,34,-1},
	/* ETH/IPV6 */ {0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,14,-1,-1,-1,-1}
};


#define PKT_TYPES_GET_HDR(tmp, state, proto)\
	do{\
		tmp = state->base + protocol_offsets_bt[ state->type ][ proto ];\
		if(tmp <= state->base )\
			tmp = NULL;\
	}while(0)

#endif //PKT_TYPES_H
